server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Routes frontend : si le fichier n’existe pas, renvoyer index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache basique pour les fichiers statiques
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|ttf|svg)$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public";
    }
}